### ISSUE TITLE
Build a link/button component (a text-only link or button with no background shape)

### ISSUE THREAD

**Issue by kblake1121** [singlestone/sugar#191]
**Link**
Text-only _link_ that when clicked/tapped, it navigates the user to a new screen. Therefore, links can never be disabled.
- [ ]  Accent color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible
- [ ]  Neutral color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible
- [ ]  Destructive color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible

**Button**
Text-only _button_ that when clicked/tapped it does something. Buttons, unlike links, can be disabled.
- [ ]  Accent color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible
- [ ]  Neutral color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible
- [ ]  Destructive color
  - [ ]  States:
    - [ ] Default
    - [ ] Hover
    - [ ] Active (mouse-down)
    - [ ] Focus-Visible

**Comment by pcmart03** [comment]
We have text only buttons. We may need additional styles if we want them to blend into paragraph text.

**Comment by ToppleTheNun** [comment]
This might just be standard `a` tags with styling.
