### ISSUE TITLE
Built a textarea component that matches the cosmetics of the text input component

### ISSUE THREAD

**Issue by kblake1121** [singlestone/sugar#212]
Need to split out the Text Area CSS from its current location in main.css.

- [ ]  Base
- [ ]  With automatic resizing

**Comment by pcmart03** [comment]
We can reuse most of the text input styles. We just need to call out anything different.

**Comment by ToppleTheNun** [comment]
I did have to make one slight tweak, which was to change the `height` CSS property to `min-height` for `<textarea>` elements due to `<textarea>` using the `rows` property to control their height.
