### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by kblake1121** [singlestone/sugar#217]
We should provide support for using Sugar with React. This would include:

- [ ]  Creating React components for each atomic element of Sugar.
- [ ]  Creating React components for each molecular element of Sugar.
- [ ]  Bundling the CSS.
- [ ]  Deciding on name on npm.
- [ ]  Publishing it to npm for use.

**Comment by pcmart03** [comment]
With tailwind, I don't think bundling css is necessary. We will need to include instructions about how to configure tailwind to include the components when it purges styles.
