### ISSUE TITLE
Revise nomenclature in code for Sugar CSS classes

### ISSUE THREAD

**Issue by kctuskey** [singlestone/sugar#235]
**Proposed format for Sugar CSS classes:**

* Component Identifier
  * Format: "sugar-[component name]"
  * Examples:
    * "sugar-button"
    * "sugar-textbox"
    * "sugar-textarea"
    * "sugar-link"
    * "sugar-checkbox"
    * "sugar-radio"
    * "sugar-select"

* Feature Identifier (only used for buttons, so far)
  * Format: "sugar-[feature name]"
  * Examples:
    * "sugar-button-with-icon"
    * "sugar-button-icon-only"

* Treatment Identifier (only used for buttons, so far)
  * Format: "sugar-[treatment name]"
  * Examples:
    * "sugar-solid"
    * "sugar-outline"
    * "sugar-ghost"

* Color Identifier (only used for buttons and links, so far)
  * Format: "sugar-[button color]"
  * Examples:
    * "sugar-accent"
    * "sugar-neutral"
    * "sugar-destructive"

**Full example Sugar CSS classes:**
* "sugar-button sugar-solid sugar-destructive"
* "sugar-button sugar-button-with-icon sugar-outline sugar-accent"
* "sugar-button sugar-button-icon-only sugar-solid sugar-neutral"
* "sugar-button sugar-button-icon-only sugar-ghost sugar-neutral"
* "sugar-link sugar-accent"
* "sugar-link sugar-neutral"
* "sugar-link sugar-destructive"
* "sugar-checkbox"
* "sugar-textbox"
* "sugar-radio"
* "sugar-select"

**Comment by kctuskey** [comment]
**Proposed format for Sugar CSS classes:**

* Component Identifier
  * Format: "sugar-[component name]"
  * Examples:
    * "sugar-button"
    * "sugar-textbox"
    * "sugar-text-input"

* Feature Identifier
  * Format: "sugar-[feature name]"
  * Examples:
    * "sugar-button-with-icon"
    * "sugar-button-icon-only"

* Variant Identifier (only used for buttons, so far)
  * Format: "sugar-[button purpose]-[button color]"
  * Examples:
    * "sugar-primary-accent"
    * "sugar-primary-neutral"
    * "sugar-primary-destructive"
    * "sugar-secondary-accent"
    * "sugar-secondary-neutral
    * "sugar-secondary-destructive""
    * "sugar-tertiary/ghost-accent"
    * "sugar-tertiary/ghost-neutral"
    * "sugar-tertiary/ghost-destructive"

**Full example Sugar CSS classes:**
* "sugar-button sugar-primary-destructive"
* "sugar-button sugar-button-with-icon sugar-secondary-accent"
* "sugar-button sugar-button-icon-only sugar-primary-neutral"

**Comment by ToppleTheNun** [comment]
The only one I'm not overly pleased with is `sugar-select-input`, but that's somewhat bikeshed-y.

**Comment by kctuskey** [comment]
We could call it `sugar-select` instead. I think the rational was to have `sugar-select-input` and `sugar-text-input` be similarly named, but that doesn't mean it has to stay that way.

**Comment by jbachmann** [comment]
I would expect the `type="?"` part of `<input />` to be the last component of the pattern if it needs to be part of the pattern at all -- `sugar-{tag}-{type}`. 

`checkbox`, `radio`, `text` are all types of `<input />`... but `<select />` is its own tag type, so that one would just be `sugar-select` with no last type component.

`sugar-input-checkbox`
`sugar-input-radio`
`sugar-input-text`
`sugar-select`

But I'm often overly rigorous. Are you using `<button /> or `<input type="button" />` for buttons? 😭 

How does `sugar-textbox` differ from `sugar-input-text` today?

**Comment by pcmart03** [comment]
I think if someone adds too many attributes, the last one class just override the any preceding classes (we'll need to test this). 

Other than that, I agree with Jordan and Terry.

**Comment by kctuskey** [comment]
I updated the top comment with what I think is our consensus. Can you react with a thumbs up emoji or a typed reply if you agree (or disagree)?

**Comment by kctuskey** [comment]
The last order of business is the nomenclature of "ghost" vs. "tertiary" for the Purpose Identifier (made up words for Sugar).

My recommendation is for "tertiary" even though it is tricky to spell. The term "ghost" is spooky and connotes color instead of purpose. Remember, a developer looking at the Sugar documentation will see "primary", "secondary", and this value near each other, and so will designers using the Sugar library in Figma designs.

**Comment by kctuskey** [comment]
I've revised the original comment with the latest naming schema for Sugar classes. Please review it and post any feedback.

**Comment by kctuskey** [comment]
I updated the description at the top of this issue with the agreed-upon nomenclature from today's call with the team.
