### ISSUE TITLE
Spike: Image snapshot testing 

### ISSUE THREAD

**Issue by BwyattSSC** [singlestone/sugar#338]
# Description 
Vitest support [image-snapshot](https://vitest.dev/guide/snapshot.html#image-snapshots) testing via [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) which would provide a visual confirmation if there were any changes that might impact how a component would look.

**Comment by ToppleTheNun** [comment]
Another tool that you can use is Playwright's component testing: https://playwright.dev/docs/test-components

**Comment by BwyattSSC** [comment]
## Preface

First time using Playwright and its VSCode Extension, as such my apologies in advance if some of the observations are verbose and potentially stating well established information about VSCode and Playwright. The location of the files are for convinced of set up and not set in stone. Looking for feedback as to where these type of test should live. Currently test are pointing to the `./tests` folder in the React example.

## Code
Branch: https://github.com/singlestone/sugar/tree/spike/playwright-component-testing
(Draft) PR: https://github.com/singlestone/sugar/pull/343 

# Playwright Test for VSCode

## Running
- https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
- No issues with running test for Chromium, Firefox and Webkit using the `Executing Using Profile` option

**__Executing Use Profile__**
![image](https://user-images.githubusercontent.com/24687048/226637376-e06245d3-3641-4e5c-b2f8-0a067edb0998.png)
- When using `Run Test`, results are reported in the Testing section of the Test Explorer but appear to only run one
**__Test Explorer__**
![image](https://user-images.githubusercontent.com/24687048/226640908-d44397bf-687f-48b5-9f23-04af0b766847.png) . Issue does not 

## Debugging
Encounter an issue when using the `Debug Test` option where the following error would display `net::ERR_SOCKS_CONNECTIONS_FAILED at http://localhost:3100/` .This is a [recent known issue](https://github.com/microsoft/playwright/issues/21762). This appears to work fine with using the Webkit profile but issue occurs when using Chromium and Firefox.

**__Error generated when running Chromium or Firefox with the debug option__**
![image](https://user-images.githubusercontent.com/24687048/226643181-42fcd6b8-5763-46a7-b892-2551688c5509.png)

This behavior does not appear to be reproducible if the Playwright option `Show browser` where it works correctly. Not sure if this is a work around to the above or just another option for debugging.

**_`Show browser` option under Testing > Playwright`_**
![image](https://user-images.githubusercontent.com/24687048/226645374-baf5d33d-23ba-4e47-bd47-1a26b10bc8f2.png)

**_VSCode Extension with FireFox Nightly build_**
![image](https://user-images.githubusercontent.com/24687048/226647065-af616c3a-b6bd-40ea-bfb9-9732dae7e34a.png)

Potentially related, upon initial installation of Playwright, Mac OS did provide a notification pertaining to Chromium but not sure how to trace back what it may have been notifying on.

# CLI
- Per [the tutorial](https://playwright.dev/docs/test-components#step-3-run-the-tests), running `npm run test-ct` will run the test which appears to run `playwright test -c playwright-ct.config.ts`
- To run with debug, append  `--debug`
- Debugging via the CLI will open its own browser window
**__Debugging via the CLI__**
![image](https://user-images.githubusercontent.com/24687048/226649261-c7091506-c1b9-4513-9ff5-711555ae8dcd.png). Based on the config, it will open the test one time for each time defined in the configuration.

# Snapshot Testing
- Snapshot test will initially fail due to generating screenshot(s) for the first time
- When test fails from snapshot, difference is reported using red/yellow ish text to emphasize the difference. Snapshot is not included when test passes (not necessarily a good or bad thing. More of an observation).

**__From report__**
![image](https://user-images.githubusercontent.com/24687048/226655416-9a3bb983-23c4-4af4-b2bc-a00aa02991a4.png)

**__Diff__**
![image](https://user-images.githubusercontent.com/24687048/226654099-5fe40a5d-0737-4ee6-a1e0-246c85069a30.png)

**__Actual__**
![45d352495c6a7a5087b6eeae4469cb6b9b179000](https://user-images.githubusercontent.com/24687048/226655725-a3d3b867-aa0d-4061-821b-5f3313b76597.png)

**__Expected__**
![39718b8ccdd86e24b234360a9daa270ebd5e16b5](https://user-images.githubusercontent.com/24687048/226655764-8b6858ca-2b60-4519-98f9-3f3a764e3900.png)

**Comment by BwyattSSC** [comment]
@kctuskey Per stand-up feedback, I included an example that makes it more visual apparent what the snapshot test is capturing. In the below example, the colors were changed from blue to purple with the snapshot test capturing each section that differed from the baseline in a red/yellowish color.

**__Diff__**
![61b943ed579498e4e305c910a801cf78f776926e](https://user-images.githubusercontent.com/24687048/226994690-bef1cad3-e1a9-4ff6-aa66-a227d667094a.png)
**__Actual__**
![44144e33e7811721df5651bf491267abb3c05bb7](https://user-images.githubusercontent.com/24687048/226994693-5247687d-8440-4767-a0ed-aedbadb8b1c3.png)
**__Expected__**
![43aeb4644d7b626ac7f50a2e98e837d5edd1ff41](https://user-images.githubusercontent.com/24687048/226994687-e0e636e4-f158-40b5-8ddb-37d5f1d5e0fc.png)
